# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81aa9c269f00214c26460ea7423760c7a93cedbfdb4fbb3ac21f4203bcd2c5f7723aebd74543890d6332c618731e7505685d574c9526a673811ed533bca7a928

test:
  secret_key_base: d04c5f9264608a8690f02d6aa88d30d0d45c6193d3a5e02e998310648781c55713b12e4d6a242be273cc19ce84e83a5273485bd4593591c4e5477ac407dc7e96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
